# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-07 23:00
from __future__ import unicode_literals

import app.NewModelTrait
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_rate', models.FloatField()),
                ('sale_rate', models.FloatField()),
                ('timestamp', models.DateTimeField(blank=True, default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
            bases=(app.NewModelTrait.NewModel, models.Model),
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField()),
            ],
            bases=(app.NewModelTrait.NewModel, models.Model),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=4)),
                ('url', models.URLField()),
            ],
        ),
        # migrations.RunSQL("IF EXISTS app_settings; INSERT INTO app_settings (value, url) VALUES (0, 'https://api.bitfinex.com/v1/book/BTCUSD');"),
    ]
